version: '2'

services:
  devel:
    build: .
    volumes:
    - .:/src
    - /mnt/data/ml/:/mnt/data/ml/
    working_dir: /src/
    command: /usr/bin/python3

  api:
    extends:
      service: devel
    command: python3 bin/baseline1.py baseline1.cfg
    ports:
    - 5000:5000

  srilm:
    build:
      context: .
      dockerfile: Dockerfile.srilm
    volumes:
    - .:/src
    - /mnt/data/ml/:/mnt/data/ml/
    working_dir: /src/
    command: ngram-count
